= `direct-bind`
:toc:
:toc-placement: macro
:toclevels: 4
:toc-title:

A ruby gem for getting direct access to function pointers. (TODO)

== Quickest start


== Installation

Install the gem and add to the application's `Gemfile` or `gems.rb` file by executing:

[source,bash]
----
$ bundle add direct-bind
----

If bundler is not being used to manage dependencies, install the gem by executing:

[source,bash]
----
$ gem install direct-bind
----

== Usage

Use `require "direct-bind"` to load the gem.

== Requirements

TODO

== Development

To use the gem locally, remember to run `bundle exec rake compile` to build the native code before you can use it. Afterwards, you can run the examples directly from the tree by running `bundle exec ruby [some example]`.

When adding new files to `ext/direct_bind_native_extension` you need to run `bundle exec rake clean compile`. This will ensure the new files get picked up and compiled correctly.

=== Installation and deployment

To install this gem onto your local machine, run `bundle exec rake install`. To release a new version, update the version number in `version.rb`, and then run `bundle exec rake release`, which will create a git tag for the version, push git commits and the created tag, and push the `.gem` file to https://rubygems.org[rubygems.org]. To run specs, run `bundle exec rake spec`.

To run all actions (build the extension, check linting, and run specs), run `bundle exec rake`.

== Contributing

Bug reports and pull requests are welcome on GitHub at https://github.com/ivoanjo/direct-bind. This project is intended to be a safe, welcoming space for collaboration, and contributors are expected to adhere to the https://github.com/ivoanjo/direct-bind/blob/master/CODE_OF_CONDUCT.adoc[code of conduct].

== Code of Conduct

Everyone interacting in the direct-bind project's codebases, issue trackers, chat rooms and mailing lists is expected to follow the https://github.com/ivoanjo/direct-bind/blob/master/CODE_OF_CONDUCT.adoc[code of conduct].
